
export const indianKeywords = [
  "validate startup idea in Bangalore India",
  "B2B leads in Bangalore India",
  "SAAS validation in Bangalore India",
  "tech cofounder in Bangalore India",
  "MVP builder in Bangalore India",
  "startup idea tester in Bangalore India",
  "market research in Bangalore India",
  "pitch deck generator in Bangalore India",
  "competitor analysis in Bangalore India",
  "startup pricing in Bangalore India",
  "validate startup idea in Mumbai India",
  "B2B leads in Mumbai India",
  "SAAS validation in Mumbai India",
  "tech cofounder in Mumbai India",
  "MVP builder in Mumbai India",
  "startup idea tester in Mumbai India",
  "market research in Mumbai India",
  "pitch deck generator in Mumbai India",
  "competitor analysis in Mumbai India",
  "startup pricing in Mumbai India",
  "validate startup idea in Delhi India",
  "B2B leads in Delhi India",
  "SAAS validation in Delhi India",
  "tech cofounder in Delhi India",
  "MVP builder in Delhi India",
  "startup idea tester in Delhi India",
  "market research in Delhi India",
  "pitch deck generator in Delhi India",
  "competitor analysis in Delhi India",
  "startup pricing in Delhi India",
  "validate startup idea in Hyderabad India",
  "B2B leads in Hyderabad India",
  "SAAS validation in Hyderabad India",
  "tech cofounder in Hyderabad India",
  "MVP builder in Hyderabad India",
  "startup idea tester in Hyderabad India",
  "market research in Hyderabad India",
  "pitch deck generator in Hyderabad India",
  "competitor analysis in Hyderabad India",
  "startup pricing in Hyderabad India",
  "validate startup idea in Pune India",
  "B2B leads in Pune India",
  "SAAS validation in Pune India",
  "tech cofounder in Pune India",
  "MVP builder in Pune India",
  "startup idea tester in Pune India",
  "market research in Pune India",
  "pitch deck generator in Pune India",
  "competitor analysis in Pune India",
  "startup pricing in Pune India",
  "validate startup idea in Chennai India",
  "B2B leads in Chennai India",
  "SAAS validation in Chennai India",
  "tech cofounder in Chennai India",
  "MVP builder in Chennai India",
  "startup idea tester in Chennai India",
  "market research in Chennai India",
  "pitch deck generator in Chennai India",
  "competitor analysis in Chennai India",
  "startup pricing in Chennai India",
  "validate startup idea in Gurgaon India",
  "B2B leads in Gurgaon India",
  "SAAS validation in Gurgaon India",
  "tech cofounder in Gurgaon India",
  "MVP builder in Gurgaon India",
  "startup idea tester in Gurgaon India",
  "market research in Gurgaon India",
  "pitch deck generator in Gurgaon India",
  "competitor analysis in Gurgaon India",
  "startup pricing in Gurgaon India",
  "validate startup idea in Noida India",
  "B2B leads in Noida India",
  "SAAS validation in Noida India",
  "tech cofounder in Noida India",
  "MVP builder in Noida India",
  "startup idea tester in Noida India",
  "market research in Noida India",
  "pitch deck generator in Noida India",
  "competitor analysis in Noida India",
  "startup pricing in Noida India",
  "validate startup idea in Ahmedabad India",
  "B2B leads in Ahmedabad India",
  "SAAS validation in Ahmedabad India",
  "tech cofounder in Ahmedabad India",
  "MVP builder in Ahmedabad India",
  "startup idea tester in Ahmedabad India",
  "market research in Ahmedabad India",
  "pitch deck generator in Ahmedabad India",
  "competitor analysis in Ahmedabad India",
  "startup pricing in Ahmedabad India",
  "validate startup idea in Kolkata India",
  "B2B leads in Kolkata India",
  "SAAS validation in Kolkata India",
  "tech cofounder in Kolkata India",
  "MVP builder in Kolkata India",
  "startup idea tester in Kolkata India",
  "market research in Kolkata India",
  "pitch deck generator in Kolkata India",
  "competitor analysis in Kolkata India",
  "startup pricing in Kolkata India",
  "validate startup idea in Bangalore India",
  "B2B leads in Bangalore India",
  "SAAS validation in Bangalore India",
  "tech cofounder in Bangalore India",
  "MVP builder in Bangalore India",
  "startup idea tester in Bangalore India",
  "market research in Bangalore India",
  "pitch deck generator in Bangalore India",
  "competitor analysis in Bangalore India",
  "startup pricing in Bangalore India",
  "validate startup idea in Mumbai India",
  "B2B leads in Mumbai India",
  "SAAS validation in Mumbai India",
  "tech cofounder in Mumbai India",
  "MVP builder in Mumbai India",
  "startup idea tester in Mumbai India",
  "market research in Mumbai India",
  "pitch deck generator in Mumbai India",
  "competitor analysis in Mumbai India",
  "startup pricing in Mumbai India",
  "validate startup idea in Delhi India",
  "B2B leads in Delhi India",
  "SAAS validation in Delhi India",
  "tech cofounder in Delhi India",
  "MVP builder in Delhi India",
  "startup idea tester in Delhi India",
  "market research in Delhi India",
  "pitch deck generator in Delhi India",
  "competitor analysis in Delhi India",
  "startup pricing in Delhi India",
  "validate startup idea in Hyderabad India",
  "B2B leads in Hyderabad India",
  "SAAS validation in Hyderabad India",
  "tech cofounder in Hyderabad India",
  "MVP builder in Hyderabad India",
  "startup idea tester in Hyderabad India",
  "market research in Hyderabad India",
  "pitch deck generator in Hyderabad India",
  "competitor analysis in Hyderabad India",
  "startup pricing in Hyderabad India",
  "validate startup idea in Pune India",
  "B2B leads in Pune India",
  "SAAS validation in Pune India",
  "tech cofounder in Pune India",
  "MVP builder in Pune India",
  "startup idea tester in Pune India",
  "market research in Pune India",
  "pitch deck generator in Pune India",
  "competitor analysis in Pune India",
  "startup pricing in Pune India",
  "validate startup idea in Chennai India",
  "B2B leads in Chennai India",
  "SAAS validation in Chennai India",
  "tech cofounder in Chennai India",
  "MVP builder in Chennai India",
  "startup idea tester in Chennai India",
  "market research in Chennai India",
  "pitch deck generator in Chennai India",
  "competitor analysis in Chennai India",
  "startup pricing in Chennai India",
  "validate startup idea in Gurgaon India",
  "B2B leads in Gurgaon India",
  "SAAS validation in Gurgaon India",
  "tech cofounder in Gurgaon India",
  "MVP builder in Gurgaon India",
  "startup idea tester in Gurgaon India",
  "market research in Gurgaon India",
  "pitch deck generator in Gurgaon India",
  "competitor analysis in Gurgaon India",
  "startup pricing in Gurgaon India",
  "validate startup idea in Noida India",
  "B2B leads in Noida India",
  "SAAS validation in Noida India",
  "tech cofounder in Noida India",
  "MVP builder in Noida India",
  "startup idea tester in Noida India",
  "market research in Noida India",
  "pitch deck generator in Noida India",
  "competitor analysis in Noida India",
  "startup pricing in Noida India",
  "validate startup idea in Ahmedabad India",
  "B2B leads in Ahmedabad India",
  "SAAS validation in Ahmedabad India",
  "tech cofounder in Ahmedabad India",
  "MVP builder in Ahmedabad India",
  "startup idea tester in Ahmedabad India",
  "market research in Ahmedabad India",
  "pitch deck generator in Ahmedabad India",
  "competitor analysis in Ahmedabad India",
  "startup pricing in Ahmedabad India",
  "validate startup idea in Kolkata India",
  "B2B leads in Kolkata India",
  "SAAS validation in Kolkata India",
  "tech cofounder in Kolkata India",
  "MVP builder in Kolkata India",
  "startup idea tester in Kolkata India",
  "market research in Kolkata India",
  "pitch deck generator in Kolkata India",
  "competitor analysis in Kolkata India",
  "startup pricing in Kolkata India"
];
export const indianQuestions = [
  "How to validate startup idea for an Indian startup?",
  "What is the best way to validate startup idea for an Indian startup?",
  "Where can I find tools to validate startup idea for an Indian startup?",
  "Is there an AI to validate startup idea for an Indian startup?",
  "Can I automate validate startup idea for an Indian startup?",
  "How to B2B leads for an Indian startup?",
  "What is the best way to B2B leads for an Indian startup?",
  "Where can I find tools to B2B leads for an Indian startup?",
  "Is there an AI to B2B leads for an Indian startup?",
  "Can I automate B2B leads for an Indian startup?",
  "How to SAAS validation for an Indian startup?",
  "What is the best way to SAAS validation for an Indian startup?",
  "Where can I find tools to SAAS validation for an Indian startup?",
  "Is there an AI to SAAS validation for an Indian startup?",
  "Can I automate SAAS validation for an Indian startup?",
  "How to tech cofounder for an Indian startup?",
  "What is the best way to tech cofounder for an Indian startup?",
  "Where can I find tools to tech cofounder for an Indian startup?",
  "Is there an AI to tech cofounder for an Indian startup?",
  "Can I automate tech cofounder for an Indian startup?",
  "How to MVP builder for an Indian startup?",
  "What is the best way to MVP builder for an Indian startup?",
  "Where can I find tools to MVP builder for an Indian startup?",
  "Is there an AI to MVP builder for an Indian startup?",
  "Can I automate MVP builder for an Indian startup?",
  "How to startup idea tester for an Indian startup?",
  "What is the best way to startup idea tester for an Indian startup?",
  "Where can I find tools to startup idea tester for an Indian startup?",
  "Is there an AI to startup idea tester for an Indian startup?",
  "Can I automate startup idea tester for an Indian startup?",
  "How to market research for an Indian startup?",
  "What is the best way to market research for an Indian startup?",
  "Where can I find tools to market research for an Indian startup?",
  "Is there an AI to market research for an Indian startup?",
  "Can I automate market research for an Indian startup?",
  "How to pitch deck generator for an Indian startup?",
  "What is the best way to pitch deck generator for an Indian startup?",
  "Where can I find tools to pitch deck generator for an Indian startup?",
  "Is there an AI to pitch deck generator for an Indian startup?",
  "Can I automate pitch deck generator for an Indian startup?",
  "How to competitor analysis for an Indian startup?",
  "What is the best way to competitor analysis for an Indian startup?",
  "Where can I find tools to competitor analysis for an Indian startup?",
  "Is there an AI to competitor analysis for an Indian startup?",
  "Can I automate competitor analysis for an Indian startup?",
  "How to startup pricing for an Indian startup?",
  "What is the best way to startup pricing for an Indian startup?",
  "Where can I find tools to startup pricing for an Indian startup?",
  "Is there an AI to startup pricing for an Indian startup?",
  "Can I automate startup pricing for an Indian startup?",
  "How to validate startup idea for an Indian startup?",
  "What is the best way to validate startup idea for an Indian startup?",
  "Where can I find tools to validate startup idea for an Indian startup?",
  "Is there an AI to validate startup idea for an Indian startup?",
  "Can I automate validate startup idea for an Indian startup?",
  "How to B2B leads for an Indian startup?",
  "What is the best way to B2B leads for an Indian startup?",
  "Where can I find tools to B2B leads for an Indian startup?",
  "Is there an AI to B2B leads for an Indian startup?",
  "Can I automate B2B leads for an Indian startup?",
  "How to SAAS validation for an Indian startup?",
  "What is the best way to SAAS validation for an Indian startup?",
  "Where can I find tools to SAAS validation for an Indian startup?",
  "Is there an AI to SAAS validation for an Indian startup?",
  "Can I automate SAAS validation for an Indian startup?",
  "How to tech cofounder for an Indian startup?",
  "What is the best way to tech cofounder for an Indian startup?",
  "Where can I find tools to tech cofounder for an Indian startup?",
  "Is there an AI to tech cofounder for an Indian startup?",
  "Can I automate tech cofounder for an Indian startup?",
  "How to MVP builder for an Indian startup?",
  "What is the best way to MVP builder for an Indian startup?",
  "Where can I find tools to MVP builder for an Indian startup?",
  "Is there an AI to MVP builder for an Indian startup?",
  "Can I automate MVP builder for an Indian startup?",
  "How to startup idea tester for an Indian startup?",
  "What is the best way to startup idea tester for an Indian startup?",
  "Where can I find tools to startup idea tester for an Indian startup?",
  "Is there an AI to startup idea tester for an Indian startup?",
  "Can I automate startup idea tester for an Indian startup?",
  "How to market research for an Indian startup?",
  "What is the best way to market research for an Indian startup?",
  "Where can I find tools to market research for an Indian startup?",
  "Is there an AI to market research for an Indian startup?",
  "Can I automate market research for an Indian startup?",
  "How to pitch deck generator for an Indian startup?",
  "What is the best way to pitch deck generator for an Indian startup?",
  "Where can I find tools to pitch deck generator for an Indian startup?",
  "Is there an AI to pitch deck generator for an Indian startup?",
  "Can I automate pitch deck generator for an Indian startup?",
  "How to competitor analysis for an Indian startup?",
  "What is the best way to competitor analysis for an Indian startup?",
  "Where can I find tools to competitor analysis for an Indian startup?",
  "Is there an AI to competitor analysis for an Indian startup?",
  "Can I automate competitor analysis for an Indian startup?",
  "How to startup pricing for an Indian startup?",
  "What is the best way to startup pricing for an Indian startup?",
  "Where can I find tools to startup pricing for an Indian startup?",
  "Is there an AI to startup pricing for an Indian startup?",
  "Can I automate startup pricing for an Indian startup?",
  "How to validate startup idea for an Indian startup?",
  "What is the best way to validate startup idea for an Indian startup?",
  "Where can I find tools to validate startup idea for an Indian startup?",
  "Is there an AI to validate startup idea for an Indian startup?",
  "Can I automate validate startup idea for an Indian startup?",
  "How to B2B leads for an Indian startup?",
  "What is the best way to B2B leads for an Indian startup?",
  "Where can I find tools to B2B leads for an Indian startup?",
  "Is there an AI to B2B leads for an Indian startup?",
  "Can I automate B2B leads for an Indian startup?",
  "How to SAAS validation for an Indian startup?",
  "What is the best way to SAAS validation for an Indian startup?",
  "Where can I find tools to SAAS validation for an Indian startup?",
  "Is there an AI to SAAS validation for an Indian startup?",
  "Can I automate SAAS validation for an Indian startup?",
  "How to tech cofounder for an Indian startup?",
  "What is the best way to tech cofounder for an Indian startup?",
  "Where can I find tools to tech cofounder for an Indian startup?",
  "Is there an AI to tech cofounder for an Indian startup?",
  "Can I automate tech cofounder for an Indian startup?",
  "How to MVP builder for an Indian startup?",
  "What is the best way to MVP builder for an Indian startup?",
  "Where can I find tools to MVP builder for an Indian startup?",
  "Is there an AI to MVP builder for an Indian startup?",
  "Can I automate MVP builder for an Indian startup?",
  "How to startup idea tester for an Indian startup?",
  "What is the best way to startup idea tester for an Indian startup?",
  "Where can I find tools to startup idea tester for an Indian startup?",
  "Is there an AI to startup idea tester for an Indian startup?",
  "Can I automate startup idea tester for an Indian startup?",
  "How to market research for an Indian startup?",
  "What is the best way to market research for an Indian startup?",
  "Where can I find tools to market research for an Indian startup?",
  "Is there an AI to market research for an Indian startup?",
  "Can I automate market research for an Indian startup?",
  "How to pitch deck generator for an Indian startup?",
  "What is the best way to pitch deck generator for an Indian startup?",
  "Where can I find tools to pitch deck generator for an Indian startup?",
  "Is there an AI to pitch deck generator for an Indian startup?",
  "Can I automate pitch deck generator for an Indian startup?",
  "How to competitor analysis for an Indian startup?",
  "What is the best way to competitor analysis for an Indian startup?",
  "Where can I find tools to competitor analysis for an Indian startup?",
  "Is there an AI to competitor analysis for an Indian startup?",
  "Can I automate competitor analysis for an Indian startup?",
  "How to startup pricing for an Indian startup?",
  "What is the best way to startup pricing for an Indian startup?",
  "Where can I find tools to startup pricing for an Indian startup?",
  "Is there an AI to startup pricing for an Indian startup?",
  "Can I automate startup pricing for an Indian startup?",
  "How to validate startup idea for an Indian startup?",
  "What is the best way to validate startup idea for an Indian startup?",
  "Where can I find tools to validate startup idea for an Indian startup?",
  "Is there an AI to validate startup idea for an Indian startup?",
  "Can I automate validate startup idea for an Indian startup?",
  "How to B2B leads for an Indian startup?",
  "What is the best way to B2B leads for an Indian startup?",
  "Where can I find tools to B2B leads for an Indian startup?",
  "Is there an AI to B2B leads for an Indian startup?",
  "Can I automate B2B leads for an Indian startup?",
  "How to SAAS validation for an Indian startup?",
  "What is the best way to SAAS validation for an Indian startup?",
  "Where can I find tools to SAAS validation for an Indian startup?",
  "Is there an AI to SAAS validation for an Indian startup?",
  "Can I automate SAAS validation for an Indian startup?",
  "How to tech cofounder for an Indian startup?",
  "What is the best way to tech cofounder for an Indian startup?",
  "Where can I find tools to tech cofounder for an Indian startup?",
  "Is there an AI to tech cofounder for an Indian startup?",
  "Can I automate tech cofounder for an Indian startup?",
  "How to MVP builder for an Indian startup?",
  "What is the best way to MVP builder for an Indian startup?",
  "Where can I find tools to MVP builder for an Indian startup?",
  "Is there an AI to MVP builder for an Indian startup?",
  "Can I automate MVP builder for an Indian startup?",
  "How to startup idea tester for an Indian startup?",
  "What is the best way to startup idea tester for an Indian startup?",
  "Where can I find tools to startup idea tester for an Indian startup?",
  "Is there an AI to startup idea tester for an Indian startup?",
  "Can I automate startup idea tester for an Indian startup?",
  "How to market research for an Indian startup?",
  "What is the best way to market research for an Indian startup?",
  "Where can I find tools to market research for an Indian startup?",
  "Is there an AI to market research for an Indian startup?",
  "Can I automate market research for an Indian startup?",
  "How to pitch deck generator for an Indian startup?",
  "What is the best way to pitch deck generator for an Indian startup?",
  "Where can I find tools to pitch deck generator for an Indian startup?",
  "Is there an AI to pitch deck generator for an Indian startup?",
  "Can I automate pitch deck generator for an Indian startup?",
  "How to competitor analysis for an Indian startup?",
  "What is the best way to competitor analysis for an Indian startup?",
  "Where can I find tools to competitor analysis for an Indian startup?",
  "Is there an AI to competitor analysis for an Indian startup?",
  "Can I automate competitor analysis for an Indian startup?",
  "How to startup pricing for an Indian startup?",
  "What is the best way to startup pricing for an Indian startup?",
  "Where can I find tools to startup pricing for an Indian startup?",
  "Is there an AI to startup pricing for an Indian startup?",
  "Can I automate startup pricing for an Indian startup?"
];
