import { Metadata } from "next";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { TamCalculator } from "@/components/free-tools/TamCalculator";
import { ChevronDown, Sparkles, ArrowRight } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Free TAM / SAM / SOM Calculator | Validexio",
  description:
    "Calculate your startup's Total Addressable Market instantly. Use our free TAM calculator to generate accurate numbers for your pitch deck.",
  keywords: [
    "TAM calculator",
    "calculate TAM SAM SOM",
    "startup market size calculator",
    "how to calculate TAM for pitch deck",
    "Total Addressable Market calculator free",
    "TAM SAM SOM formula",
    "startup metrics calculator",
    "market sizing tool",
  ],
  alternates: {
    canonical: "https://validexio.com/free-tools/tam-calculator",
  },
};

const faqs = [
  {
    q: "What is TAM?",
    a: "<strong>Total Addressable Market</strong> is the total global demand for your product or service. If 100% of the people who could potentially buy your product did so, this is the revenue you would generate. VCs look for large TAMs (often $1B+).",
  },
  {
    q: "What is SAM?",
    a: "<strong>Serviceable Available Market</strong> is the segment of the TAM targeted by your products and services which is within your geographical or operational reach. It is the realistic portion of the market you can serve right now.",
  },
  {
    q: "What is SOM?",
    a: "<strong>Serviceable Obtainable Market</strong> is the portion of your SAM that you can realistically capture in the short term (years 1-3). This factors in your current resources, competition, and sales capabilities. It is your immediate revenue goal.",
  },
  {
    q: "What is a good TAM for a startup?",
    a: "Venture capitalists typically look for a TAM of at least <strong>$1 Billion</strong> for a startup to be considered fundable. However, for a bootstrapped Micro-SaaS, a TAM of $10M–$50M can be highly lucrative.",
  },
  {
    q: "What is CAC?",
    a: "<strong>Customer Acquisition Cost</strong> is the total cost of sales and marketing required to earn a new customer. A healthy SaaS business usually aims to keep this number as low as possible while scaling.",
  },
  {
    q: "What is LTV?",
    a: "<strong>Lifetime Value</strong> is the total amount of money a customer is expected to spend on your products during their lifetime as a customer. Higher retention heavily increases this metric.",
  },
  {
    q: "LTV:CAC Ratio",
    a: "The <strong>LTV to CAC Ratio</strong> measures the relationship between the lifetime value of a customer and the cost of acquiring that customer. An optimal ratio is generally considered to be 3:1 or higher.",
  },
  {
    q: "What is MRR?",
    a: "<strong>Monthly Recurring Revenue</strong> is the predictable total revenue generated by your business from all active subscriptions in a single month. It is the lifeblood of a SaaS startup.",
  },
  {
    q: "Gross Margin",
    a: "<strong>Gross Margin</strong> is the percentage of revenue you retain after accounting for the direct costs associated with running your service (e.g., server hosting, LLM API costs, database operations).",
  },
  {
    q: "Payback Period",
    a: "The <strong>Payback Period</strong> is the number of months it takes for a customer's gross profit to cover their initial Customer Acquisition Cost. Investors prefer a payback period of under 12 months.",
  },
];

export default function TamCalculatorPage() {
  return (
    <main className="min-h-screen bg-[#FDFCF8] text-[#1B1716] font-sans selection:bg-[#75070C]/20 selection:text-[#75070C] overflow-x-hidden">
      <Navbar />

      {/* JSON-LD Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([
            {
              "@context": "https://schema.org",
              "@type": "WebApplication",
              name: "Free TAM / SAM / SOM Calculator",
              applicationCategory: "BusinessApplication",
              description:
                "A free interactive tool to calculate Total Addressable Market (TAM), Serviceable Available Market (SAM), and Serviceable Obtainable Market (SOM) for startups.",
              operatingSystem: "Web",
              offers: {
                "@type": "Offer",
                price: "0",
                priceCurrency: "USD",
              },
            },
            {
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: faqs.map((f) => ({
                "@type": "Question",
                name: f.q,
                acceptedAnswer: {
                  "@type": "Answer",
                  text: f.a.replace(/<[^>]+>/g, ""),
                },
              })),
            },
          ]).replace(/</g, "\\u003c"),
        }}
      />

      {/* Hero Section */}
      <section className="pt-28 pb-10 sm:pt-36 sm:pb-14 px-4 relative overflow-hidden">
        {/* Background orb */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[90vw] max-w-2xl h-[400px] bg-cherry/5 rounded-full blur-[80px] pointer-events-none" />

        <div className="max-w-2xl mx-auto text-center relative z-10">
          {/* Free badge */}
          <div className="inline-flex items-center gap-2 bg-cherry/10 border border-cherry/20 text-cherry text-xs font-black uppercase tracking-widest px-4 py-2 rounded-full mb-6">
            <Sparkles className="w-3.5 h-3.5" />
            Free Tool for Founders
          </div>

          <h1 className="text-3xl sm:text-5xl md:text-6xl font-black tracking-tight text-[#1B1716] mb-4 leading-[1.1]">
            Calculate Your{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-cherry to-[#D97706]">
              TAM / SAM / SOM
            </span>
          </h1>

          <p className="text-base sm:text-lg text-[#1B1716]/60 max-w-xl mx-auto mb-8 leading-relaxed">
            Stop guessing your market size. Get accurate, investor-ready numbers
            for your pitch deck — instantly and free.
          </p>

          {/* Feature pills */}
          <div className="flex flex-wrap items-center justify-center gap-2 mb-2">
            {["Live calculations", "6 key metrics", "No sign-up needed"].map(
              (f) => (
                <span
                  key={f}
                  className="inline-flex items-center gap-1 bg-white border border-[#1B1716]/10 text-[#1B1716]/60 text-xs font-semibold px-3 py-1.5 rounded-full"
                >
                  <span className="w-1.5 h-1.5 bg-emerald-400 rounded-full" />
                  {f}
                </span>
              )
            )}
          </div>
        </div>
      </section>

      {/* Calculator */}
      <section className="px-4 pb-16 sm:pb-24 relative z-10">
        <div className="max-w-4xl mx-auto">
          <TamCalculator />
        </div>
      </section>

      {/* CTA Bridge */}
      <section className="px-4 pb-16">
        <div className="max-w-2xl mx-auto bg-[#1B1716] rounded-3xl p-8 sm:p-10 text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-cherry/20 rounded-full blur-[80px] pointer-events-none -translate-y-1/2 translate-x-1/2" />
          <div className="relative z-10">
            <p className="text-xs font-black uppercase tracking-widest text-cherry mb-3">
              Go Beyond Calculations
            </p>
            <h2 className="text-2xl sm:text-3xl font-black text-white mb-4 tracking-tight">
              Get the full validation report in 60 seconds
            </h2>
            <p className="text-sm text-white/50 mb-6 max-w-md mx-auto leading-relaxed">
              Validexio analyzes your idea, competitors, and unit economics — then
              delivers a complete GTM kit, fake-door code, and tech architecture.
            </p>
            <Link
              href="/"
              className="inline-flex items-center gap-2 bg-cherry text-white font-black text-sm px-8 py-4 rounded-xl shadow-lg shadow-cherry/30 hover:bg-[#810100] transition-colors"
            >
              Validate My Idea — $39
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="px-4 pb-24">
        <div className="max-w-2xl mx-auto">
          <div className="text-center mb-10">
            <h2 className="text-2xl sm:text-3xl font-black text-[#1B1716] tracking-tight mb-2">
              Startup Metrics Glossary
            </h2>
            <p className="text-sm text-[#1B1716]/50">
              Every key metric explained in plain English
            </p>
          </div>

          <div className="space-y-2">
            {faqs.map((faq) => (
              <details
                key={faq.q}
                className="group bg-white border border-[#1B1716]/8 rounded-2xl overflow-hidden [&_summary::-webkit-details-marker]:hidden"
              >
                <summary className="flex items-center justify-between px-5 py-4 cursor-pointer font-bold text-sm sm:text-base text-[#1B1716] select-none list-none">
                  {faq.q}
                  <ChevronDown className="w-4 h-4 sm:w-5 sm:h-5 text-cherry shrink-0 ml-3 transition-transform duration-300 group-open:-rotate-180" />
                </summary>
                <div
                  className="px-5 pb-4 text-sm text-[#1B1716]/60 leading-relaxed border-t border-[#1B1716]/5 pt-3"
                  dangerouslySetInnerHTML={{ __html: faq.a }}
                />
              </details>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
